name: niv
version: 0.1.0
license: MIT
author: Nicolas Mattia <nicolas@nmattia.com>
maintainer: Nicolas Mattia <nicolas@nmattia.com>
copyright: (c) 2019 Nicolas Mattia
category: Development
github: deckgo/wai-lambda
synopsis: Easy dependency management for Nix projects
description: Easy dependency management for Nix projects.

ghc-options:
    - -Wall
    - -Werror

    # For macOS: https://github.com/gibiansky/IHaskell/issues/942
    - -optP-Wno-nonportable-include-path

extra-source-files:
    - README.md

dependencies:
    - aeson
    - aeson-pretty
    - base
    - bytestring
    - concurrent-output
    - directory
    - file-embed
    - filepath
    - github
    - gitrev
    - hashable
    - mtl
    - optparse-applicative
    - process
    - string-qq
    - text
    - unliftio
    - unordered-containers

library:
    source-dirs:
        - src
    dependencies:
        - aeson
        - github
        - tasty
        - tasty-hunit
        - unordered-containers
        - concurrent-output

executables:
    niv:
        main: Niv.main
        source-dirs: app
        data-files:
            - nix/sources.nix
        dependencies:
            - niv
    niv-test:
        main: NivTest.main
        source-dirs: app
        dependencies:
            - tasty
            - niv
