name: niv

ghc-options:
    - -Wall
    - -Werror

executable:
    source-dirs: . # remove when https://github.com/nmattia/snack/pull/96 is merged
    main: Main.hs
    dependencies:
        - aeson
        - aeson-pretty
        - directory
        - string-qq
        - filepath
        - github
        - mtl
        - optparse-applicative
        - unordered-containers
        - temporary
