name: "netlify deploy"
on:
  push:
    branches:
      - master
jobs:
  netlify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "deploy to netlify"
      uses: netlify/actions/cli@375963b92b795c7b979927c580dd6f2a65ebcf28
      with:
        args: deploy --dir=./site --message="$GITHUB_SHA" --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
